In [1]:
from scipy import linalg

import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])

In [3]:
# Matrix Multiplication
A.dot(A)

array([[ 7, 10],
       [15, 22]])

In [4]:
# Matrix Norm
linalg.norm(A)

5.477225575051661

In [5]:
# CHECK: Matrix Norm
np.sqrt(sum([x**2 for x in range(1, 5)]))

5.477225575051661

In [6]:
# Calc determinant
linalg.det(A)

-2.0

In [7]:
print(A)

[[1 2]
 [3 4]]


In [8]:
# Calc Matrix Inverse
A_inv = linalg.inv(A)

In [9]:
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
# CHECK: Inverse X original = identity matrix
A_inv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [11]:
# Compute Eigenvalues

In [12]:
x, y = linalg.eig(A)

x0, x1 = x[0], x[1]

y0, y1 = y[:, 0], y[:, 1]

In [13]:
# Verify normal equation #1

print(A.dot(y0))

print(x0 * y0)

[ 0.30697009 -0.21062466]
[ 0.30697009-0.j -0.21062466+0.j]


In [14]:
# Verify normal equation #2

print(A.dot(y1))

print(x1 * y1)

[-2.23472698 -4.88542751]
[-2.23472698+0.j -4.88542751+0.j]


In [15]:
# verify eigenvalue decomposition
y.dot(np.diag(x).dot(linalg.inv(y)))

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [16]:
# Calc singular value decomposition
u, s, v = linalg.svd(A)

In [17]:
# U is symmetric & orthogonal
print(u)

print(u.dot(u.T))

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[[1. 0.]
 [0. 1.]]


In [18]:
# Sigma is a diagonal matrix (if A is invertible)
print(np.diag(s))

[[5.4649857  0.        ]
 [0.         0.36596619]]


In [19]:
# V is symmetric
print(v)

# V is orthogonal
print(v.dot(v.T))

[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
[[1. 0.]
 [0. 1.]]


In [20]:
# CHECK: singular value decomposition recovers A
u.dot(np.diag(s).dot(v))

array([[1., 2.],
       [3., 4.]])